### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by duchesnay** [neurospin/pylearn-epac#24]
Install
Examples
Plug my objects within EPAC (p-values clusteur level)
Internals
- Principles top-down/Bottum up
- Classes: Pipe, Splitter/Sclicer

**Comment by JinpengLI** [comment]
I have finished the very first version of documentation. @duchesnay @duboism Feel free to read and **extend** the documentation if you want. Thank you.

http://neurospin.github.io/pylearn-epac
