### ISSUE TITLE
How to dump self defined node and use it in epac mapper

### ISSUE THREAD

**Issue by JinpengLI** [neurospin/pylearn-epac#28]

**Comment by JinpengLI** [comment]
It seems that there is no open source project can dump class definition. 

For this moment, to solve that problem, we could create a new file **"self_defined_nodes.py"** just containing the definition of the class **self_defined_node**. 

```
from self_defined_nodes import self_defined_node
```

On all the computers that you run program, you need to setup the PYTHONPATH containing **"self_defined_nodes.py"**

References:
http://stackoverflow.com/questions/9127714/attributeerror-module-object-has-no-attribute-newperson
http://stackoverflow.com/questions/3614379/attributeerror-when-unpickling-an-object

**Comment by GaelVaroquaux** [comment]
> It seems that there is no open source project can dump class definition.

Maybe dill can be useful:
http://dev.danse.us/trac/pathos/browser/dill

**Comment by JinpengLI** [comment]
Many thanks @GaelVaroquaux . It seems that **dill** is a good solution to our case. I will make a test very soon.

**Comment by JinpengLI** [comment]
I have made a test, and I found that dill cannot pickle the classes that inherit **object**. It doesn't mention in http://trac.mystic.cacr.caltech.edu/project/pathos/wiki/dill （Dill cannot yet pickle these standard， types:: frame, generator, traceback）， or maybe yes but I fail to find it. 

However, it is really a good library to dump the definition of the other classes. Therefore, I have changed the base class as empty for those classes that need to be dumped. User now can run self-defined node in epac. 

```
class OA(object):
    def __init__(self):
        self.a = 1
        self.b = 2
    def test(self):
        print "hello oa"
        self.a = self.a + self.b

import dill as pickle
dump_str = pickle.dumps(OA())
f = open("/tmp/dump_str", "wb")
f.write(dump_str)
f.close()

```

Open by another python script:

```

import dill as pickle
f = open("/tmp/dump_str", "rb")
dump_str = f.read()
f.close()
obj = pickle.loads(dump_str)
obj.test()

```

AttributeError: 'module' object has no attribute 'OA'

**Comment by JinpengLI** [comment]
Jinpeng,

This works:

> > > class OA(object):
> > > ...   def **init**(self):
> > > ...     self.a = 1
> > > ...     self.b = 2
> > > ...   def test(self):
> > > ...     print "hello oa"
> > > ...     self.a = self.a + self.b
> > > ...
> > > import dill as pickle
> > > _oa = pickle.dumps(OA())
> > > 
> > > obj = pickle.loads(_oa)
> > > obj.test()
> > > hello oa

So it definitely can pickle a class based on object.

However, if I follow your script, I also get an AttributeError.
It is because dill is assuming the class OA is defined in **main**,
which when you shut down the interpreter session... it no longer
is defined in **main**.  This should only an issue for object-based
classes defined in **main** that are serialized across two python
sessions.  So, yes, there is some more work to do in that case.

Note that if your class OA is defined in a file from which it is
imported, then there should also be no AttributeError.

xxx@xxx>$ python

> > > from foo import OA
> > > import dill as pickle
> > > f = open('tmpdill.pkl','wb')
> > > pickle.dump(OA(), f)
> > > f.close()

xxx@xxx>$ python

> > > import dill as pickle
> > > f = open('tmpdill.pkl','rb')
> > > obj = pickle.load(f)
> > > obj.test()
> > > hello oa

Which does pickle, because the reference to OA is now to 'foo'
and not '**main**'.  So there is a small limitation for object-based
classes, but they do indeed pickle for most cases.

Thanks for your email.
Mike McKerns
