### ISSUE TITLE
mapper issue from virtual list

### ISSUE THREAD

**Issue by JinpengLI** [neurospin/pylearn-epac#29]

**Comment by JinpengLI** [comment]
Done. The reason is that

```
BaseNode::get_path_from_node
...
path_key = key.replace(parent_key, "").lstrip(conf.SEP) 
...
```

when

```
key="CV/CV(nb=1)/SelectKBest"
parent_key="CV"
```

then 

```
key="/(nb=1)/SelectKBest"
```

In fact, we want to remove only the left part of "CV". This bug has been fixed in the branch of "fix_multiprocess". @duboism Free feel to let me know if I can push to master cause maybe you have some other updates.

Best,
Jinpeng

**Comment by duboism** [comment]
As far as I am concerned, you can push to master.
