### ISSUE TITLE
multi processes and its parent process test

### ISSUE THREAD

**Issue by JinpengLI** [neurospin/pylearn-epac#48]
Test on multi-processes memory consumption and its parent process memory consumption.  When numpy.array from parent process is not changed in child process, I am not sure if it will increase memory consumption.

**Comment by JinpengLI** [comment]
```
# -*- coding: utf-8 -*-

import os
import numpy as np
import time

def child(test_mat):
    print 'A new child', os.getpid()
    print np.sum(test_mat)
    time.sleep(5)
    os._exit(0)

def parent():
    test_mat = np.random.random((1, 100000000))
    print np.sum(test_mat)
    while True:
        time.sleep(5)
        newpid = os.fork()
        if newpid == 0:
            child(test_mat)
        else:
            pids = (os.getpid(), newpid)
            print "parent : %d, child %d" % pids
        if raw_input() == "q":
            break

if __name__ == "__main__":
    parent()

```

If we use **fork** to create a new process, the child process will consume as much memory as the parent memory. It cannot reuse the matrix from parent process even we don't change the matrix.

Here is a memory consumption from  $ htop :
![screenshot from 2013-11-04 09 17 28](https://f.cloud.github.com/assets/3331085/1463341/94cfae44-4529-11e3-8d1b-ae4beaa126e1.png)

**Comment by JinpengLI** [comment]
```
from multiprocessing import Pool
import numpy as np
import time


# @profile
def test_memo_func(x):
    print np.sum(x)
    time.sleep(5)
    return 1


# @profile
def main_func():
    pool = Pool(processes=2)
    big_matrix = np.random.random((1, 25000000))
    big_matrixes = []    
    for i in xrange(20):
        big_matrixes.append(big_matrix)
    for i in xrange(len(big_matrixes)):
        print np.sum(big_matrix) 
    time.sleep(20)
    res_list = pool.map(test_memo_func, big_matrixes)
    return 0

if __name__ == "__main__":
    main_func()

```

If we use **pool** to create a new process, the child process will consume as much memory as the parent memory as well. It cannot reuse the matrix from parent process even we don't change the matrix.

**pool** creates two sub-processes under master process.

![screenshot from 2013-11-04 09 28 49](https://f.cloud.github.com/assets/3331085/1463408/6402cd02-452c-11e3-81e0-cb06b522e2f7.png)

**Comment by JinpengLI** [comment]
Hi @duchesnay @BenoitDamota ,

It is about a problem mentioned in the last meeting. It is not important, just leave it alone if you are busy. The problem is to re-use matrix in child process from parent process. Here you are the test code. It seems that we cannot re-use matrix from parent process. The child process will always make a copy from parent process.

Regards,
Jinpeng

**Comment by BenoitDamota** [comment]
Hi @JinpengLI,

Ok, 2 simple things about copy-on-write mechanism in Python:

1 - Unix or Unix-like systems only copy memory when modified. You would use this interesting property ;-) but ...
2 - Python stores the objects with their metadata and in these metadata you have the references counter.

So, if you call a function with your data as parameters you increase the ref. count.
here is one hack/workaround I abuse:

```
from multiprocessing import Pool
import numpy as np

def test_memo_func():
    print np.sum(x)
    time.sleep(5)
    return 1

def main_func():
    pool = Pool(processes=2)
    for i in xrange(20):
        pool.apply_async(test_memo_func)
    pool.close()
    pool.join()
    return 0

if __name__ == "__main__":
    x = np.random.random((1, 25000000))
    main_func()

```

Best regards,
Benoit

**Comment by JinpengLI** [comment]
Hi @BenoitDamota ,

The script misses **import time**. The function test_memo_func raises error.

```
from multiprocessing import Pool
import numpy as np
import time


def test_memo_func():
    print np.sum(x)
    time.sleep(5)
    return 1


def main_func():
    pool = Pool(processes=2)
    for i in xrange(20):
        pool.apply_async(test_memo_func)
    pool.close()
    pool.join()
    return 0


if __name__ == "__main__":
    x = np.random.random((1, 25000000))
    main_func()

```

It won't increase the memory consumption. That is a cool feature! I can improve epac.

Thanks,
Jinpeng
